config/routes.rb
Rails.application.routes.draw do
  resources :recipes, only: [:index, :show]
  root to: 'recipes#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipe.rb
# frozen_string_literal: true

class Recipe
  attr_accessor :id, :title, :image_id, :tags_ids, :description, :chef_id

  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def image_url
    return nil if image_id.blank?

    Rails.cache.fetch(image_id, expires_in: 24.hours) do
      JSON.parse(
        client.get(
          path: "/spaces/#{ENV['CONTENTFUL_SPACE_ID']}/assets/#{image_id}?access_token=#{ENV['CONTENTFUL_TOKEN']}"
        ).body
      ).dig('fields', 'file', 'url').gsub('//', 'https://')
    end
  end

  def tags
    return [] if tags_ids.blank?

    tags_ids.map do |tag_id|
      Rails.cache.fetch(tag_id, expires_in: 24.hours) do
        JSON.parse(
          client.get(
            path: "/spaces/#{ENV['CONTENTFUL_SPACE_ID']}/entries/#{tag_id}?access_token=#{ENV['CONTENTFUL_TOKEN']}"
          ).body
        ).dig('fields', 'name')
      end
    end
  end

  def chef_name
    return nil if chef_id.blank?

    Rails.cache.fetch(chef_id, expires_in: 24.hours) do
      JSON.parse(
        client.get(
          path: "/spaces/#{ENV['CONTENTFUL_SPACE_ID']}/entries/#{chef_id}?access_token=#{ENV['CONTENTFUL_TOKEN']}"
        ).body
      ).dig('fields', 'name')
    end
  end

  private

  def client
    Excon.new(ENV['CONTENTFUL_BASE_URL'])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recipes_controller.rb
# frozen_string_literal: true

class RecipesController < ApplicationController
  caches_page :show

  def index
    result = Recipes::RecipesRetrieverService.call
    flash[:notice] = result.error unless result.success?
    @recipes = result.value
  end

  def show
    result = Recipes::RecipeRetrieverService.call(allowed_params[:id])
    flash[:notice] = result.error unless result.success?
    @recipe = result.value
  end

  private

  def allowed_params
    params.permit!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    options = [:hard_wrap, :autolink, :no_intra_emphasis, :fenced_code_blocks]
    Markdown.new(text, *options).to_html.html_safe
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mycontentful</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body class="bg-gray-40">
    <div class="container mx-auto max-w-3xl flex flex-col items-left p-7">
      <%= yield %>
    </div>
  </body>
</html>

app/views/recipes/index.html.erb
<h1 class="font-mono text-6xl font-bold mt-10 mb-10 text-yellow-500">Marley Recipes</h1>

<ul class="container mx-auto flex flex-col items-center">
  <% if @recipes.present? %>
    <% @recipes.each do |recipe| %>
      <li class="p-3">
        <%= link_to recipe_url(recipe.id) do %>
          <h2 class="font-mono text-3xl font-bold mb-3 text-gray-500 hover:text-gray-700"><%= recipe.title %></h2>
          <img src="<%= recipe.image_url %>" alt="Nome da receita" class="rounded" />
        <% end %>
      </li>
    <% end %>
  <% else %>
    <% flash.each do |type, msg| %>
      <h3 class="font-mono text-3xl font-bold mt-10 mb-10 text-yellow-500">
        <%= msg %>
      </h3>
    <% end %>
  <% end %>
</ul>

app/views/recipes/show.html.erb
<div class="pb-30" style="margin-bottom: 100px">

<% if @recipe.present? %>

  <h1 class="font-mono text-6xl font-bold mt-10 mb-3 text-yellow-500">
    <%= @recipe.title %>
  </h1>

  <h4 class="font-mono text-3xl font-bold mb-3">
    <%= @recipe.chef_name %>
  </h4>

  <img src="<%= @recipe.image_url %>" alt="Nome da receita" />

  <p class="font-sans text-lg mt-5 mb-5" id="md" data-description="<%= @recipe.description %>"></p>

  <% if @recipe.tags.present? %>
    <h3 class="mr-2 mt-5 font-mono text-2xl font-bold" style="margin-bottom: 20px">
      Tags: <%= @recipe.tags.join(', ') %>
    </h3>
  <% end %>

<% else %>
  <% flash.each do |type, msg| %>
    <h3 class="font-mono text-3xl font-bold mt-10 mb-10 text-yellow-500">
      <%= msg %>
    </h3>
  <% end %>
<% end %>
<%= link_to 'Back to home', root_path, class: 'bg-yellow-500 hover:bg-yellow-700 p-2 text-white font-mono rounded' %>
</div>